# Generated by Django 2.0.5 on 2018-06-11 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('link', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('price', models.IntegerField()),
                ('recurring', models.BooleanField(default=False)),
                ('was_cancelled', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'All Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('planned_budget', models.IntegerField()),
                ('planned_amount', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('occurance', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Tag Set',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.SubscriptionPlan'),
        ),
    ]
