# Generated by Django 2.0.5 on 2018-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0003_auto_20180611_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='personal_rating',
            field=models.IntegerField(default=0),
        ),
    ]
